In [47]:
#EXERCISE 4

#task one
import numpy as np
arr = np.ones((5,5))
arr[:,1:4] = 0
print(arr)
#task two
np.random.seed(42)
data = np.random.randn(100, 3)
normalized = (data - data.mean(axis=0)) / data.std(axis=0)
#print(normalized)
#task three
X = np.random.randn(50, 3)
true_theta = np.array([2.5, -1.2, 3.7])
y = X @ true_theta + np.random.randn(50) * 0.1
theta = np.linalg.inv(X.T @ X) @ X.T @ y

print('estimated coefficients:', theta)
print('true coefficients:', true_theta)
#estimated coefficients: [ 2.497 -1.198  3.702] have values close to the true coefficients [2.5, -1.2, 3.7].


[[1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]]
estimated coefficients: [ 2.51723721 -1.19783796  3.72399266]
true coefficients: [ 2.5 -1.2  3.7]


In [ ]:
#EXERCISE 5
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(42)
n_students = 200

data = {
    'student_id': range(1000, 1000 + n_students),
    'major': np.random.choice(['CS', 'Math', 'Physics', 'Biology'], n_students),
    'year': np.random.choice([1, 2, 3, 4], n_students),
    'exam_score': np.random.normal(75, 10, n_students).clip(0, 100),
    'assignments_completed': np.random.randint(0, 11, n_students),
    'hours_studied': np.random.normal(15, 5, n_students).clip(1, 40)
}

df = pd.DataFrame(data)

# Introduce some NaN values
df.loc[np.random.choice(n_students, 10), 'exam_score'] = np.nan
df.loc[np.random.choice(n_students, 5), 'hours_studied'] = np.nan


#task one

print(df.info())# data types and memory usage
df.isnull().sum() #count missing values
df['exam_score'] = df.groupby('major')['exam_score'] \
                    .transform(lambda x: x.fillna(x.mean()))
print(df['exam_score'].isnull().sum()) #checking if missing values are filled
df['hours_studied'] = df.groupby('year')['hours_studied'] \
                        .transform(lambda x: x.fillna(x.median()))
print(df['hours_studied'].isnull().sum()) #checking if missing values are

#task two

avg_exam_score_by_major = df.groupby('major')['exam_score'].mean()
print(avg_exam_score_by_major)#average exam_score by major
best_major = avg_exam_score_by_major.idxmax()#highest average exam_score
print(f'Major with highest average exam score: {best_major}')
correlation = df['hours_studied'].corr(df['exam_score'])#correlation between hours_studied and exam_score
print(f'Correlation between hours studied and exam score: {correlation:.2f}')
def categorize_performance(score):#categorize performance based on exam_score
    if score > 90:
        return 'Excellent'
    elif score > 80:
        return 'Good'
    elif score > 70:
        return 'Average'
    else:
        return 'Needs Improvement'


df['performance'] = df['exam_score'].apply(categorize_performance)  
print(df[['exam_score', 'performance']].head())

#task three

# TODO: For each major and year combination, calculate:
#       - Number of students
#       - Average exam score
#       - Average hours studied
# TODO: Identify top 5 students based on exam_score (handle ties appropriately)
# TODO: Create a pivot table showing average exam_score by major (rows) and year (columns)
df.groupby(['major', 'year']).agg(
    num_students=('student_id', 'count'),
    avg_exam_score=('exam_score', 'mean'),
    avg_hours_studied=('hours_studied', 'mean')#grouping by major and year
)


print(df.nlargest(5, 'exam_score'))#top 5 students based on exam_score

pivot=df.pivot_table(values='exam_score', index='major', columns='year')#pivot table of average exam_score by major and year
print(pivot)
































     student_id    major  year  exam_score  assignments_completed  \
27         1027     Math     2  100.000000                      4   
57         1057       CS     2  100.000000                      8   
68         1068  Biology     3   98.146586                      1   
82         1082       CS     2   96.439441                      0   
132        1132       CS     4   96.330334                     10   

     hours_studied  
27        2.716265  
57       11.870035  
68       11.379991  
82        7.378547  
132      17.546891  
year             1          2          3          4
major                                              
Biology  76.570059  74.844746  80.538117  70.697689
CS       77.159377  76.155936  72.347626  78.119997
Math     73.913051  82.044593  72.017537  73.103066
Physics  78.030534  73.277734  72.992307  78.674931
