In [137]:
#EXERCISE 4

#task one
import numpy as np
arr = np.ones((5,5))
arr[:,1:4] = 0
print(arr)
#task two
np.random.seed(42)
data = np.random.randn(100, 3)
normalized = (data - data.mean(axis=0)) / data.std(axis=0)
#print(normalized)
#task three
X = np.random.randn(50, 3)
true_theta = np.array([2.5, -1.2, 3.7])
y = X @ true_theta + np.random.randn(50) * 0.1
theta = np.linalg.inv(X.T @ X) @ X.T @ y

print('estimated coefficients:', theta)
print('true coefficients:', true_theta)
#estimated coefficients: [ 2.497 -1.198  3.702] have values close to the true coefficients [2.5, -1.2, 3.7].


[[1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]]
estimated coefficients: [ 2.51723721 -1.19783796  3.72399266]
true coefficients: [ 2.5 -1.2  3.7]


In [138]:
#EXERCISE 5
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(42)
n_students = 200

data = {
    'student_id': range(1000, 1000 + n_students),
    'major': np.random.choice(['CS', 'Math', 'Physics', 'Biology'], n_students),
    'year': np.random.choice([1, 2, 3, 4], n_students),
    'exam_score': np.random.normal(75, 10, n_students).clip(0, 100),
    'assignments_completed': np.random.randint(0, 11, n_students),
    'hours_studied': np.random.normal(15, 5, n_students).clip(1, 40)
}

df = pd.DataFrame(data)

# Introduce some NaN values
df.loc[np.random.choice(n_students, 10), 'exam_score'] = np.nan
df.loc[np.random.choice(n_students, 5), 'hours_studied'] = np.nan


#task one

print(df.info())# data types and memory usage
df.isnull().sum() #count missing values
df['exam_score'] = df.groupby('major')['exam_score'] \
                    .transform(lambda x: x.fillna(x.mean()))
print(df['exam_score'].isnull().sum()) #checking if missing values are filled
df['hours_studied'] = df.groupby('year')['hours_studied'] \
                        .transform(lambda x: x.fillna(x.median()))
print(df['hours_studied'].isnull().sum()) #checking if missing values are

#task two

avg_exam_score_by_major = df.groupby('major')['exam_score'].mean()
print(avg_exam_score_by_major)#average exam_score by major
best_major = avg_exam_score_by_major.idxmax()#highest average exam_score
print(f'Major with highest average exam score: {best_major}')
correlation = df['hours_studied'].corr(df['exam_score'])#correlation between hours_studied and exam_score
print(f'Correlation between hours studied and exam score: {correlation:.2f}')
def categorize_performance(score):#categorize performance based on exam_score
    if score > 90:
        return 'Excellent'
    elif score > 80:
        return 'Good'
    elif score > 70:
        return 'Average'
    else:
        return 'Needs Improvement'


df['performance'] = df['exam_score'].apply(categorize_performance)  
print(df[['exam_score', 'performance']].head())

#task three

i
df.groupby(['major', 'year']).agg(
    num_students=('student_id', 'count'),
    avg_exam_score=('exam_score', 'mean'),
    avg_hours_studied=('hours_studied', 'mean')#grouping by major and year
)


print(df.nlargest(5, 'exam_score'))#top 5 students based on exam_score

pivot=df.pivot_table(values='exam_score', index='major', columns='year')#pivot table of average exam_score by major and year
print(pivot)
































<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   student_id             200 non-null    int64  
 1   major                  200 non-null    str    
 2   year                   200 non-null    int64  
 3   exam_score             190 non-null    float64
 4   assignments_completed  200 non-null    int64  
 5   hours_studied          195 non-null    float64
dtypes: float64(2), int64(3), str(1)
memory usage: 9.5 KB
None
0
0
major
Biology    75.503150
CS         76.425184
Math       74.683689
Physics    75.406509
Name: exam_score, dtype: float64
Major with highest average exam score: CS
Correlation between hours studied and exam score: -0.06
   exam_score        performance
0   68.199753  Needs Improvement
1   77.322537            Average
2   77.930725            Average
3   67.856486  Needs Improvement
4   93.657745          Excellent


NameError: name 'i' is not defined

In [ ]:
#EXERCISE 6
import matplotlib.pyplot as plt
import seaborn as sns
 
 #task one
fig, ax =plt.subplots(1, 2, figsize=(10, 5))
sns.histplot(df['exam_score'], bins=10,  edgecolor='black', kde=True, ax=ax[0])#histogram of exam scores
ax[0].set_title(' Histogram plot of Exam Scores')
ax[0].set_xlabel('Exam Score')
ax[0].set_ylabel('Frequency')

sns.boxplot(df['exam_score'], ax=ax[1])#box plot of exam scores
ax[1].set_title('Box Plot of Exam Scores')
ax[1].set_xlabel('Exam Score')
ax[1].set_ylabel('Frequency')



sns.scatterplot(data=df, x='hours_studied', y='exam_score', hue='major', alpha=0.6)  # scatter plot with colors based on major
plt.xlabel('Hours Studied')
plt.ylabel('Exam Score')
plt.title('Hours Studied vs Exam Score')
plt.show()

# task three
fig, ax = plt.subplots(2, 2, figsize=(12, 10))
categories = ['CS', 'Math', 'Physics', 'Biology']
values = avg_exam_score_by_major

ax[0, 0].bar(categories, values)
ax[0, 0].set_xlabel('Major')
ax[0, 0].set_ylabel('Average Exam Score')
ax[0, 0].set_title('Average Exam Score by Major')

pivot = df.pivot_table(values='exam_score', index='major', columns='year')
print(pivot)

sns.countplot(data=df, x='year', ax=ax[0, 1])  # count plot of number of students by year
ax[0, 1].set_title('Number of Students by Year')

correlation = df[['exam_score', 'hours_studied']].corr()
sns.heatmap(correlation, annot=True, cmap='coolwarm', ax=ax[1, 0])  # heat map of correlation matrix
ax[1, 0].set_title('Correlation Matrix of Numerical Columns')

sns.violinplot(data=df, x='performance', y='exam_score', ax=ax[1, 1])  # violin plot of exam score distribution by performance category
ax[1, 1].set_title('Exam Score Distribution by Performance Category')







In [ ]:
#EXERCISE 7
from matplotlib.pylab import rint


np.random.seed(42)
n_customers = 500

ages = np.random.randint(18, 70, n_customers)
income = np.random.normal(50000, 20000, n_customers).clip(15000, 150000)
purchase_freq = np.random.poisson(5, n_customers)
avg_purchase_value = np.random.normal(100, 30, n_customers).clip(10, 500)

customers = pd.DataFrame({
    'age': ages,
    'income': income,
    'purchase_frequency': purchase_freq,
    'avg_purchase_value': avg_purchase_value
})

#Task one
churn_risk = 1 - (purchase_freq / purchase_freq.max())  # churn risk based on purchase frequency
clv = purchase_freq * avg_purchase_value * (1 + churn_risk)
customers['clv'] = clv  # adding CLV column to the dataframe


#Task two

customers['age_group']= pd.cut(customers['age'], bins=[18, 25, 35, 50, 70], labels=['18-25', '26-35', '36-50', '51-70'])#creating customers age groups


#task three
customers.groupby('age_group').agg(
    num_customers=('age', 'count'),
    avg_income=('income', 'mean'),
    avg_clv=('clv', 'mean'),
    total_clv=('clv', 'sum')
)

# task four
print(customers.nlargest(int(0.1 * len(customers)), 'clv'))#top 10% of customers by CLV



#task five
fig, ax =plt.subplots(1, 3, figsize=(16, 5))
sns.scatterplot(data=customers, x='income', y='clv', hue='age_group', alpha=0.6, ax=ax[0])  # scatter plot with colors based on age group
ax[0].set_xlabel('customer income')
ax[0].set_ylabel('CLV')
ax[0].set_title('Customer Income vs CLV')


categories = ['18-25', '26-35', '36-50', '51-70']
values = customers.groupby('age_group')['clv'].mean()
ax[1].bar(categories, values)
ax[1].set_xlabel('Age Group')
ax[1].set_ylabel('Average CLV')
ax[1].set_title('Average CLV by Age Group')

correlation = customers[['income', 'clv']].corr()
sns.heatmap(correlation, annot=True, cmap='coolwarm', ax=ax[2])  # heat map of correlation matrix
ax[2].set_title('Correlation Matrix of customers Income and CLV')
















First it was a very insightful process of manipulating and visualising data using python.
From the begining i discovered one could not just define a matrix but design values in required preferences using comands like Matrix.ones etc.in that same light i learnt that when a matrix is normalised, its estimated coeffient gets close to its true coefficient.
moving forward key findings where about grouping data in which i learnt how to perform data cleaning by handling missing values using group imputation, which allows on to fill in missing data based on the mean  of specific groups (e.g., by major or year). I also learned how to conduct data analysis by calculating summary statistics, identifying trends, and visualizing relationships between variables. Additionally, I gained experience in grouping and aggregating data to derive insights, such as average exam scores by major and year, and creating visualizations like scatter plots, bar charts, and heatmaps to better understand the data.
