In [47]:
#EXERCISE 4

#task one
import numpy as np
arr = np.ones((5,5))
arr[:,1:4] = 0
print(arr)
#task two
np.random.seed(42)
data = np.random.randn(100, 3)
normalized = (data - data.mean(axis=0)) / data.std(axis=0)
#print(normalized)
#task three
X = np.random.randn(50, 3)
true_theta = np.array([2.5, -1.2, 3.7])
y = X @ true_theta + np.random.randn(50) * 0.1
theta = np.linalg.inv(X.T @ X) @ X.T @ y

print('estimated coefficients:', theta)
print('true coefficients:', true_theta)
#estimated coefficients: [ 2.497 -1.198  3.702] have values close to the true coefficients [2.5, -1.2, 3.7].


[[1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]]
estimated coefficients: [ 2.51723721 -1.19783796  3.72399266]
true coefficients: [ 2.5 -1.2  3.7]


In [ ]:
#EXERCISE 5
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(42)
n_students = 200

data = {
    'student_id': range(1000, 1000 + n_students),
    'major': np.random.choice(['CS', 'Math', 'Physics', 'Biology'], n_students),
    'year': np.random.choice([1, 2, 3, 4], n_students),
    'exam_score': np.random.normal(75, 10, n_students).clip(0, 100),
    'assignments_completed': np.random.randint(0, 11, n_students),
    'hours_studied': np.random.normal(15, 5, n_students).clip(1, 40)
}

df = pd.DataFrame(data)

# Introduce some NaN values
df.loc[np.random.choice(n_students, 10), 'exam_score'] = np.nan
df.loc[np.random.choice(n_students, 5), 'hours_studied'] = np.nan


#task one

print(df.info())# data types and memory usage
df.isnull().sum() #count missing values
df['exam_score'] = df.groupby('major')['exam_score'] \
                    .transform(lambda x: x.fillna(x.mean()))
print(df['exam_score'].isnull().sum()) #checking if missing values are filled
df['hours_studied'] = df.groupby('year')['hours_studied'] \
                        .transform(lambda x: x.fillna(x.median()))
print(df['hours_studied'].isnull().sum()) #checking if missing values are

#task two

avg_exam_score_by_major = df.groupby('major')['exam_score'].mean()
print(avg_exam_score_by_major)#average exam_score by major
best_major = avg_exam_score_by_major.idxmax()#highest average exam_score
print(f'Major with highest average exam score: {best_major}')
correlation = df['hours_studied'].corr(df['exam_score'])#correlation between hours_studied and exam_score
print(f'Correlation between hours studied and exam score: {correlation:.2f}')
def categorize_performance(score):#categorize performance based on exam_score
    if score > 90:
        return 'Excellent'
    elif score > 80:
        return 'Good'
    elif score > 70:
        return 'Average'
    else:
        return 'Needs Improvement'


df['performance'] = df['exam_score'].apply(categorize_performance)  
print(df[['exam_score', 'performance']].head())

#task three
# Task 3: Advanced Dashboard (9 points)
# TODO: Create a 2x2 subplot figure containing:
#       1. Bar chart: Average exam score by major
#       2. Count plot: Number of students by year
#       3. Heat map: Correlation matrix of numerical columns
#       4. Violin plot: Exam score distribution by performance category
# TODO: Adjust layout, add titles, and ensure readability









# 1. Bar chart: Average exam score by major










<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   student_id             200 non-null    int64  
 1   major                  200 non-null    str    
 2   year                   200 non-null    int64  
 3   exam_score             190 non-null    float64
 4   assignments_completed  200 non-null    int64  
 5   hours_studied          195 non-null    float64
dtypes: float64(2), int64(3), str(1)
memory usage: 9.5 KB
None
0
0
major
Biology    75.503150
CS         76.425184
Math       74.683689
Physics    75.406509
Name: exam_score, dtype: float64
Major with highest average exam score: CS
Correlation between hours studied and exam score: -0.06
   exam_score        performance
0   68.199753  Needs Improvement
1   77.322537            Average
2   77.930725            Average
3   67.856486  Needs Improvement
4   93.657745          Excellent
